---

- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster

- name: 'Determine cluster type'
  command: oc version
  register: oc_version
  ignore_errors: yes

- name: 'Set facts'
  set_fact:
    cluster: "{{ 'openshift' if 'openshift' in oc_version.stdout else 'kubernetes' }}"

- name: 'Include variables based on ansible version'
  include_vars: ansible_26.yml
  when: ansible_version.full is version('2.6', '>=')

- name: Validate Admin User and Password
  fail:
    msg: "Mediawiki Admin User and Password cannot be the same value!"
  when:
  - mediawiki_admin_user == mediawiki_admin_pass
  - apb_action == "provision"

- name: "Set mediawiki objects state={{ state }}"
  k8s_raw:
    state: '{{ state }}'
    definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - service.yaml
    - pvc.yaml

- name: "Set mediawiki route state={{ state }}"
  openshift_raw:
    state: '{{ state }}'
    definition: "{{ lookup('template', 'route.yaml') | from_yaml }}"
  when: cluster == 'openshift'

- name: "Set mediawiki deployment state={{ state }}"
  openshift_raw:
    state: '{{ state }}'
    definition: "{{ lookup('template', 'deployment.yaml') | from_yaml }}"

- name: "Update last operation"
  asb_last_operation:
    description: "100%: Done"
  when: in_cluster
